apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: l5qtds5sb-nodejs 
  janus-idp.io/tekton: l5qtds5sb-nodejs
  backstage.io/kubernetes-id: l5qtds5sb-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: l5qtds5sb-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  